apiVersion: apps/v1
kind: Deployment
metadata:
  name: k7s-deployment
spec:
  selector:
    matchLabels:
      app: k7
  replicas: 2
  template:
    metadata:
      labels:
        app: k7
    spec:
      containers:
        - name: k7s-containers
          image: srikarkurma5445/k7s:latest
          ports:
            - containerPort: 8085
